apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
spec:
  provider:
    vault:
      path: innabox
      caProvider:
        type: Secret
        namespace: vault
        name: server-ca-certificate
        key: tls.crt
      auth:
        kubernetes:
          mountPath: jwt/innabox-reader
          role: innabox-reader
          serviceAccountRef:
            name: vault-secret-reader
            namespace: external-secrets-operator
      server: https://vault.vault.svc:8200
      version: v2
