apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-dns
commonLabels:
  app: custom-dns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: dns-config
    options:
      disableNameSuffixHash: true
    files:
    - Corefile
    - nerc-ocp-infra.rc.fas.harvard.edu.zone
