apiVersion: v1
kind: Service
metadata:
  name: custom-dns
spec:
  ports:
  - name: domain-tcp
    port: 8053
    protocol: TCP
    targetPort: domain-tcp
  - name: domain-udp
    port: 8053
    protocol: UDP
    targetPort: domain-udp
