apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: dex
    namespace: dex
    repo: https://charts.dexidp.io
    version: 0.23.0
    includeCRDs: true
    skipTests: true
    releaseName: dex
    valuesFile: values.yaml
