apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-controller-token
  namespace: innabox
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["controller"]
    verbs: ["create"]
