apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nerc-infra-routed
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: nerc-infra
      type: vlan
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-routes: true
      vlan:
        base-iface: enp7s0f1np1
        id: 2076
      mtu: 1500
