apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nese-storage
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: enp7s0f1np1
      type: ethernet
      state: up
      ipv4:
        enabled: true
        dhcp: true
        auto-routes: true
      mtu: 9000
