apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:

- target:
    kind: ArgoCD
    name: openshift-gitops
  patch: |
    - op: add
      path: /spec/server/host
      value: gitops.apps.hypershift1.nerc.mghpcc.org
