apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common

- certificates
- console
- clusterrolebindings
- machineconfigs
- nodenetworkconfigurationpolicies
- feature/odf
- externalsecrets
- dns

- ../../bundles/external-secrets-clustersecretstore
- ../../bundles/metallb
- ../../bundles/nerc-certificate-clusterissuers
- ../../bundles/virt
- ../../bundles/acm-cim

components:
  - ../../components/nerc-oauth-github

configMapGenerator:
- name: cluster-monitoring-config
  namespace: openshift-monitoring
  options:
    disableNameSuffixHash: true
  files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml

patches:
- target:
    kind: ClusterIssuer
    name: letsencrypt-.*-dns01
  patch: |
    - op: replace
      path: /spec/acme/solvers/0/selector/dnsZones/0
      value: hypershift1.nerc.mghpcc.org
- path: clustersecretstores/nerc-cluster-secrets_patch.yaml
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: 1a8790fb1d1c5f46c510
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: nerc/hypershift1/openshift-config/github-client-secret
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/hypershift1/aws-route53-credentials
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.hypershift1.nerc.mghpcc.org
- target:
    kind: ExternalSecret
  patch: |
    - op: replace
      path: /spec/secretStoreRef
      value:
        kind: ClusterSecretStore
        name: nerc-cluster-secrets
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: add
      path: /metadata/namespace
      value: openshift-operators
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: nerc/hypershift1/openshift-operators/aws-route53-credentials
- target:
    kind: Subscription
    name: odf-operator
    namespace: openshift-storage
  patch: |
    - op: replace
      path: /spec/channel
      value: stable-4.17
- target:
    kind: Subscription
    name: acm
    namespace: open-cluster-management
  patch: |
    - op: replace
      path: /spec/channel
      value: release-2.12
