apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

components:
- ../../../../components/localca

resources:
- ../../base
- vault-config.yaml
- allow-discovery.yaml
- vault-certificate.yaml
