issuer: https://dex.apps.hypershift1.nerc.mghpcc.org

web:
  tlsCert: /certs/tls.crt
  tlsKey: /certs/tls.key

storage:
  type: sqlite3
  config:
    file: /data/dex.db

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: vault
    name: Vault
    redirectURIs:
      - https://vault.apps.hypershift1.nerc.mghpcc.org/oidc/callback
      - https://vault.apps.hypershift1.nerc.mghpcc.org/ui/vault/auth/oidc/oidc/callback
    secretEnv: VAULT_CLIENT_SECRET

connectors:
  - type: openshift
    id: openshift
    name: OpenShift
    config:
      issuer: https://kubernetes.default.svc
      clientID: system:serviceaccount:dex:dex
      clientSecret: $OPENSHIFT_CLIENT_SECRET
      redirectURI: https://dex.apps.hypershift1.nerc.mghpcc.org/callback
      groups:
        - system:authenticated
      rootCA: /run/secrets/kubernetes.io/serviceaccount/ca.crt
